# Generated by Django 5.2.15 on 2026-06-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnexoTabla151At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mes", models.TextField(null=True)),
                ("gerencia_regional", models.TextField(null=True)),
                (
                    "valor_porcentaje",
                    models.FloatField(db_column="valor_%%", null=True),
                ),
                ("estado_operativo", models.CharField(max_length=255, null=True)),
                ("estado_operativo_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_15_1_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoTabla152At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mes", models.TextField(null=True)),
                ("gerencia_regional", models.TextField(null=True)),
                (
                    "valor_porcentaje",
                    models.FloatField(db_column="valor_%%", null=True),
                ),
                ("estado_operativo", models.CharField(max_length=255, null=True)),
                ("estado_operativo_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_15_2_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoTabla153At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mes", models.TextField(null=True)),
                ("gerencia_regional", models.TextField(null=True)),
                (
                    "valor_porcentaje",
                    models.FloatField(db_column="valor_%%", null=True),
                ),
                ("estado_operativo", models.CharField(max_length=255, null=True)),
                ("estado_operativo_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_15_3_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoTabla21At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gerencia_regional", models.TextField(null=True)),
                ("eareps", models.TextField(null=True)),
                ("zona_afectada", models.TextField(null=True)),
                (
                    "afectacion_mw",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tension_maxima",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tension_minima",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "tension_nominal",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                ("causa", models.TextField(null=True)),
                ("inicio", models.DateTimeField(null=True)),
                ("duracion", models.TextField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_2_1_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoTabla22At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gerencia_regional", models.TextField(null=True)),
                ("eareps", models.TextField(null=True)),
                ("zona_afectada", models.TextField(null=True)),
                (
                    "afectacion_mw",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "frecuencia_maxima_pu",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "frecuencia_minima_pu",
                    models.DecimalField(decimal_places=4, max_digits=20, null=True),
                ),
                ("causa", models.TextField(null=True)),
                ("inicio", models.DateTimeField(null=True)),
                ("duracion", models.TextField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_2_2_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoTabla64At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("causa", models.TextField(null=True)),
                ("gerencia", models.TextField(null=True)),
                ("mes", models.TextField(null=True)),
                ("cantidad", models.BigIntegerField(null=True)),
                ("estado_operativo", models.CharField(max_length=255, null=True)),
                ("estado_operativo_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_6_4_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoTabla65At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("causa", models.TextField(null=True)),
                ("gerencia", models.TextField(null=True)),
                ("mes", models.TextField(null=True)),
                ("cantidad", models.BigIntegerField(null=True)),
                ("estado_operativo", models.CharField(max_length=255, null=True)),
                ("estado_operativo_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_6_5_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnexoTabla66At",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("causa", models.TextField(null=True)),
                ("gerencia", models.TextField(null=True)),
                ("mes", models.TextField(null=True)),
                ("cantidad", models.BigIntegerField(null=True)),
                ("estado_operativo", models.CharField(max_length=255, null=True)),
                ("estado_operativo_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."anexo_tabla_6_6_at"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AppAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_dashboard", "Can view Dashboard"),
                    ("view_map", "Can view Mapa Nacional"),
                    ("manage_users", "Can manage Users"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BitacoraAlertaConsumo",
            fields=[
                (
                    "id_registro",
                    models.IntegerField(
                        db_column="id_registro", primary_key=True, serialize=False
                    ),
                ),
                ("id_alerta", models.IntegerField(db_column="id_alerta")),
                ("id_nivel", models.IntegerField(db_column="id_nivel", null=True)),
                (
                    "mensaje_especifico",
                    models.TextField(db_column="mensaje_especifico", null=True),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(db_column="fecha_evaluacion", null=True),
                ),
            ],
            options={
                "db_table": '"electricidad"."bitacora_alertas_consumos"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BitacoraAlertaPermiso",
            fields=[
                (
                    "numero_permiso",
                    models.CharField(
                        db_column="NumeroPermiso",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_alerta", models.IntegerField(db_column="id_alerta")),
                ("id_nivel", models.IntegerField(db_column="id_nivel", null=True)),
                (
                    "mensaje_especifico",
                    models.TextField(db_column="mensaje_especifico", null=True),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(db_column="fecha_evaluacion", null=True),
                ),
            ],
            options={
                "db_table": '"electricidad"."bitacora_alertas_permisos"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DashboardConsumo",
            fields=[
                (
                    "id_registro",
                    models.IntegerField(
                        db_column="id_registro", primary_key=True, serialize=False
                    ),
                ),
                (
                    "id_ro_reporte_operacion",
                    models.IntegerField(db_column="IdROReporteOperacion", null=True),
                ),
                (
                    "numero_permiso",
                    models.TextField(db_column="NumeroPermiso", null=True),
                ),
                ("numero_turno", models.TextField(db_column="NumeroTurno", null=True)),
                (
                    "permisionario",
                    models.TextField(db_column="Permisionario", null=True),
                ),
                ("anio", models.IntegerField(db_column="Anio", null=True)),
                ("mes_ini", models.TextField(db_column="MesIni", null=True)),
                ("mes_fin", models.TextField(db_column="MesFin", null=True)),
                ("tipo_periodo", models.TextField(db_column="TipoPeriodo", null=True)),
                (
                    "fecha_recepcion",
                    models.DateTimeField(db_column="FechaRecepcion", null=True),
                ),
                (
                    "total_capacidad",
                    models.DecimalField(
                        db_column="TotalCapacidad",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "generacion_bruta",
                    models.DecimalField(
                        db_column="GeneracionBruta",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "consumo_auxiliar",
                    models.DecimalField(
                        db_column="ConsumoAuxiliar",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "generacion_neta",
                    models.DecimalField(
                        db_column="GeneracionNeta",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("tecnologia", models.TextField(db_column="Tecnologia", null=True)),
                ("combustible", models.TextField(db_column="Combustible10", null=True)),
            ],
            options={
                "db_table": '"electricidad"."dashboard_consumos"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DashboardPermiso",
            fields=[
                (
                    "numero_permiso",
                    models.TextField(
                        db_column="NumeroPermiso", primary_key=True, serialize=False
                    ),
                ),
                ("numero_turno", models.TextField(db_column="NumeroTurno", null=True)),
                (
                    "numero_expediente",
                    models.CharField(
                        db_column="Numero_Expediente", max_length=255, null=True
                    ),
                ),
                (
                    "permisionario",
                    models.TextField(db_column="Permisionario", null=True),
                ),
                (
                    "razon_social_autorizada",
                    models.CharField(
                        db_column="Razon_Social_Autorizada", max_length=255, null=True
                    ),
                ),
                ("modalidad", models.TextField(db_column="Modalidad", null=True)),
                ("tecnologia", models.TextField(db_column="Tecnologia", null=True)),
                (
                    "fuente_energia",
                    models.CharField(
                        db_column="Fuente_Energia", max_length=255, null=True
                    ),
                ),
                (
                    "total_capacidad",
                    models.DecimalField(
                        db_column="TotalCapacidad",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "central_entidad_federativa",
                    models.TextField(db_column="CentralEntidadFederativa", null=True),
                ),
                (
                    "central_municipio",
                    models.TextField(db_column="CentralMunicipio", null=True),
                ),
                (
                    "estatus_legal",
                    models.CharField(
                        db_column="Estatus_Legal", max_length=255, null=True
                    ),
                ),
                (
                    "estatus_bdi",
                    models.CharField(
                        db_column="Estatus_BDI", max_length=255, null=True
                    ),
                ),
                (
                    "fecha_otorgamiento",
                    models.DateField(db_column="Fecha_Otorgamiento", null=True),
                ),
                (
                    "fecha_operacion",
                    models.DateField(db_column="Fecha_Operacion", null=True),
                ),
            ],
            options={
                "db_table": '"electricidad"."dashboard_permisos"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DatosDashboardGeorreferenciado",
            fields=[
                (
                    "numero_permiso",
                    models.TextField(
                        db_column="NumeroPermiso", primary_key=True, serialize=False
                    ),
                ),
                ("anio", models.IntegerField(db_column="Anio", null=True)),
                ("tipo_periodo", models.TextField(db_column="TipoPeriodo", null=True)),
                ("mes_ini", models.TextField(db_column="MesIni", null=True)),
                ("mes_fin", models.TextField(db_column="MesFin", null=True)),
                (
                    "permisionario",
                    models.TextField(db_column="Permisionario", null=True),
                ),
                ("modalidad", models.TextField(db_column="Modalidad", null=True)),
                (
                    "central_entidad_federativa",
                    models.TextField(db_column="CentralEntidadFederativa", null=True),
                ),
                (
                    "central_municipio",
                    models.TextField(db_column="CentralMunicipio", null=True),
                ),
                (
                    "total_capacidad",
                    models.DecimalField(
                        db_column="TotalCapacidad",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "generacion_bruta",
                    models.DecimalField(
                        db_column="GeneracionBruta",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "consumo_auxiliar",
                    models.DecimalField(
                        db_column="ConsumoAuxiliar",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "generacion_neta",
                    models.DecimalField(
                        db_column="GeneracionNeta",
                        decimal_places=4,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "tecnologia_instalada",
                    models.CharField(
                        db_column="Tecnologia_Instalada", max_length=255, null=True
                    ),
                ),
                (
                    "fuente_energia",
                    models.CharField(
                        db_column="Fuente_Energia", max_length=255, null=True
                    ),
                ),
                (
                    "estatus_legal",
                    models.CharField(
                        db_column="Estatus_Legal", max_length=255, null=True
                    ),
                ),
                ("geom_texto", models.TextField(db_column="geom_texto", null=True)),
            ],
            options={
                "db_table": '"electricidad"."datos_dashboard_georreferenciado"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GerenciaRegional",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("region_control", models.CharField(max_length=255, null=True)),
                ("geom", models.TextField(null=True)),
            ],
            options={
                "db_table": '"datos_complementarios"."gerencias_control"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RNTLineaTransmision",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre_lt", models.TextField(null=True)),
                ("caracteristica", models.TextField(null=True)),
                ("tension_kv", models.BigIntegerField(null=True)),
                ("categ_kv", models.BigIntegerField(null=True)),
                ("longi_km", models.FloatField(null=True)),
                ("tension_la", models.TextField(null=True)),
                ("geometry", models.TextField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."rnt_lineas_transmision_2024"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RNTSubestacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cve_ent", models.TextField(null=True)),
                ("nom_ent", models.TextField(null=True)),
                ("cve_mun", models.TextField(null=True)),
                ("nom_mun", models.TextField(null=True)),
                ("subestacion", models.TextField(null=True)),
                ("fase", models.TextField(null=True)),
                ("tension_kv", models.BigIntegerField(null=True)),
                ("x_long", models.FloatField(null=True)),
                ("y_lat", models.FloatField(null=True)),
                ("geometry", models.TextField(null=True)),
            ],
            options={
                "db_table": '"electricidad"."rnt_subestaciones_2024"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaElectrico",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("region_control", models.CharField(max_length=255, null=True)),
                ("geom", models.TextField(null=True)),
            ],
            options={
                "db_table": '"datos_complementarios"."sistemas_electricos"',
                "managed": False,
            },
        ),
    ]
