# Generated by Django 5.2.15 on 2026-06-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appaccess",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("view_overview", "Módulo: Resumen Técnico"),
                    ("view_mix", "Módulo: Matriz de Generación"),
                    ("view_reports", "Módulo: Alertas y Bitácora"),
                    ("view_infra", "Módulo: Infraestructura de Red"),
                    ("view_desempeno", "Módulo: Desempeño SEN"),
                    ("view_disturbios", "Módulo: Disturbios SEN"),
                    ("manage_users", "Módulo: Gestión de Usuarios"),
                    ("manage_roles", "Módulo: Gestión de Roles"),
                ],
            },
        ),
    ]
